# Production Config Settings
spring:
  application:
    name: citylibrarycliapp_v1-in-production
  main:
    banner-mode: off
  # Datasource config settings
  datasource:
    url: jdbc:mysql://localhost:3306/cs425-swe-202503-librarydb
    username: cs425-swe-202503-librarydb-sys
    password: test1234
  # JPA/Hibernate config settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: off
